# Change these first
owner: billflix # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Plex
    url: 192.168.1.200:32400
  - name: Request
    url: https://request.billflix.media
  - name: Monitor
    url: https://monitor.billflix.media
  - name: Help
    url: https://help.billflix.media
  - name: Bitwarden
    url: https://bitwarden.billflix.media

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: plex.billflix.media
  baseUrl: /upptime
  logoUrl: https://static-00.iconduck.com/assets.00/plex-new-icon-1024x1024-ucrk264e.png
  name: Upptime
  introTitle: "**Billflix Uptime Status**"
  introMessage: This is a monitoring page which uses **real-time** data to check if Billflix and the associated services are online. 
  navbar:
    - title: Requests
      href: https://request.billflix.media
    - title: Help
      href: https://help.billflix.media
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
